config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  get 'dashboard/index'
  root "static_pages#home"
  get "help", to: "static_pages#help"
  get "about" ,to: "static_pages#about"
  get "contact" ,to: "static_pages#contact"
  get "signup" ,to: 'users#new'
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  get "dashboard", to: "dashboard#index"
  
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :toys
end

app/models/toy.rb
class Toy < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc)}
  validates :name, presence: true
  has_rich_text :description
  validates :description, presence: true, length: { maximum: 255 }
  has_many_attached :images
  validates :images, content_type: { in: [:png, :jpg, :jpeg, :gif], message: "Images should have valid image format(png,jpg,jpeg,gif)."}
  validates :images, size: { less_than: 5.megabytes , message: 'should less than 5MB.' }

  self.per_page = 6

  def date_listed
    created_at.strftime("%B %d, %Y at %I:%M%p")
  end

  def truncated_description
    description.to_plain_text.truncate(50)
  end
  
end

app/controllers/toys_controller.rb
class ToysController < ApplicationController
  before_action :logged_in_user, only: [:show, :new, :edit, :destroy]
  before_action :admin_user, only: :destroy
  # before_action :correct_user, only: :edit
  
  def index
    @toys = Toy.includes(:user, :rich_text_description, images_attachments: :blob).paginate(page: params[:page])
  end

  def show
    @toy = Toy.includes(images_attachments: :blob).find(params[:id])
  end

  def new
    @toy = current_user.toys.build
  end

  def create
    @toy = current_user.toys.build(toy_params)
  
    if @toy.save
      flash[:success] = "Toy saved successfully."
      redirect_to toys_url
    else
      render "new", status: :unprocessable_entity
    end
  end

  def edit
    @toy = Toy.find(params[:id])
  end

  def update
    @toy = Toy.find(params[:id])

    if @toy.update(toy_params)
      flash[:success] = "Toy updated successfully."
      redirect_to @toy
    else
      render "edit", status: :unprocessable_entity
    end
  end

  def destroy
    Toy.find(params[:id]).destroy
    flash[:success] = "Toy deleted successfully."
    redirect_to toys_url
  end

  private

  def toy_params
    params.require(:toy).permit(:name, :description, :user_id, images: [])
  end
  
  def correct_user
    @toy = current_user.toys.find_by(id: params[:id])
    redirect_to root_url if @toy.nil?
  end
  
end

app/helpers/toys_helper.rb
module ToysHelper
end

app/views/toys/_file_form.html.erb
<div class="dropzone dropzone-default dz-clickable" data-controller="dropzone" data-dropzone-max-file-size="5" data-dropzone-accepted-files="image/*" data-dropzone-max-files="5" data-upload-multiple="true">
  <%= f.file_field :images, multiple: true, direct_upload: true, data: { dropzone_target: 'input' } %>
  <div class="dropzone-msg dz-message needsclick">
    <h3 class="dropzone-msg-title">Drop file here or click to upload.</h3>
    <span class="dropzone-msg-desc">The file should less than 5mb, allowed file types are: jpeg, png, gif</span>
    <span class="dropzone-msg-desc">Files should have a file extension, otherwise, it will not be uploaded.</span>
  </div>
</div>

app/views/toys/_form.html.erb
<%= form_with(model: toy, id:"#{dom_id(toy)}") do |f| %>
  <%= render "shared/error_messages", object: f.object%>

  <%= f.label :name, class: "form-label" %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :description, class: "form-label" %>
  <%= f.rich_text_area :description, class:"mb-4"%>

  <%= render "image_field", form: f%>

  <%= f.submit "Create", class: "btn btn-primary", data: { disable_with: "Please wait..."} %>

<% end %>

app/views/toys/_image_field.html.erb
<div class="dropzone dropzone-default dz-clickable" data-controller="dropzone" data-dropzone-max-file-size="5" data-dropzone-accepted-files="image/*" data-dropzone-max-files="5" data-upload-multiple="true">
  <%= form.file_field :images, multiple: true, direct_upload: true, data: { dropzone_target: 'input' } %>
  <div class="dropzone-msg dz-message needsclick">
    <h3 class="dropzone-msg-title">Drop file here or click to upload.</h3>
    <span class="dropzone-msg-desc">The file should less than 5mb, allowed file types are: jpeg, png, gif</span>
    <span class="dropzone-msg-desc">Files should have a file extension, otherwise, it will not be uploaded.</span>
  </div>
</div>

app/views/toys/_toy.html.erb
<div class="col" id="<%= dom_id toy %>">
  <div class="card mb-3" style="max-width: 540px;">
    <div class="row g-0">
      <div class="col-md-4">
        <% if toy.images.attached? %>
          <%= image_tag(toy.images.first.variant(resize_to_fit: [100, 100]), alt: toy.name, class: "img-fluid rounded-start", style:"width:600px;height:200px;") %>
        <% else %>
          <%= image_tag("https://developers.elementor.com/docs/assets/img/elementor-placeholder-image.png", alt: toy.name, class: "img-fluid rounded-start", style:"width:600px;height:200px;")%>
        <% end %>
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title"><%= link_to toy.name, toy_path(toy) %></h5>
          <p class="card-text">
            <%= toy.truncated_description %>
          </p>
          <p class="card-text"> Listed by <%= toy.user.name%> </p>
          <p class="card-text">
            <small class="text-muted">
              <%= toy.date_listed%>
            </small>
          </p>
          <p><%= link_to "View" , toy_path(toy), class: "btn btn-primary" %></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/toys/_toy_item.html.erb
  <h1><%= toy.name %></h1>
  <div data-controller="carousel" id="carouselExampleIndicators" class="carousel slide carousel-fade" data-mdb-ride="carousel">

    <div class="carousel-inner mb-5">
      <div class="carousel-item active" data-carousel-target="main">
        <img src="<%= url_for toy.images.first %>" class="d-block w-100" style="width:500px;height:600px;"/>
      </div>
    </div>

    <div class="carousel-indicators" style="margin-bottom: -20px;">
      <% if toy.images.attached? %>
        <% toy.images.each_with_index do |img, index| %>
          <button data-action="carousel#click" data-carousel-url-param=<%= url_for img %> type="button" style="width: 100px;">
            <%= image_tag(img.variant(resize_to_limit: [500, 500]), class:"d-block w-100")%>
          </button>
        <% end %>
      <% else %>
      <p>No image available.</p>
      <% end %>
    </div>
  </div>
  <h2><%= toy.description %></h2>

app/views/toys/edit.html.erb
<% provide(:title, "Edit toy")%>
<h1>Edit Toy</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form", toy: @toy%>
  </div>
</div>

app/views/toys/index.html.erb
<% provide(:title, "All Toys")%>

<h1>Toys</h1>
<p>View listings.</p>
<%= link_to "Create new", new_toy_path, class: "btn btn-primary btn-lg" if logged_in? %>
<div class="container">
  <%= will_paginate %>

    <%#= turbo_frame_tag "toys" do %>
      <div class="row row-cols-3 g-3">
        <%= render @toys %>
      </div>
    <%# end %>

  <%= will_paginate %>
</div>

app/views/toys/new.html.erb
<% provide(:title, "New Toy")%>
<h1>New Toy</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form", toy: @toy%>
  </div>
</div>

app/views/toys/show.html.erb
<% provide(:title, "Toy-#{@toy.name}")%>

<div class="container">

  <%= render "toy_item", toy: @toy %>

  <%= link_to "Edit Toy", edit_toy_path(@toy), class: "btn btn-primary" if logged_in? && @toy.user == current_user || current_user.admin? %>
  <%= link_to "Delete", @toy, class: "btn btn-danger",  data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} if logged_in? && current_user.admin?  %>

</div>