config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  get 'dashboard/index'
  root "static_pages#home"
  get "help", to: "static_pages#help"
  get "about" ,to: "static_pages#about"
  get "contact" ,to: "static_pages#contact"
  get "signup" ,to: 'users#new'
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  get "dashboard", to: "dashboard#index"
  
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :toys
end

app/views/layouts/_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag "application", media: "all", "data-turbo-track" => "reload" %>
<%= javascript_importmap_tags %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="https://www.michaelhartl.com/">Michael Hartl</a>
    </small>
   <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="https://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<!--header class="navbar navbar-fixed-top navbar-inverse" data-controller="dropdown">
  <div class="container">
    <%= link_to 'sample app', root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%#= link_to 'Home', root_path %></li>
        <li><%#= link_to "Toys", toys_path %></li>
        <li><%#= link_to 'Help', help_path %></li>
        <% if logged_in? %>
          <li><%#= link_to "Users", users_path  %></li>          
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-action="click->dropdown#toggle">
              Account<b class="caret" ></b>
            </a>
            <ul data-dropdown-target="toggleable" class="dropdown-content hidden">
              <li><%#= link_to "Profile", user_path(current_user) %></li>
              <li><%#= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%#= link_to "Logout", logout_path, data: { turbo_method: :delete } %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%#= link_to 'Login', login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header-->

<nav class="navbar navbar-expand-lg navbar-dark bg-dark text-white" data-controller="dropdown">
  <div class="container-fluid" style="width:65%">
    <button class="navbar-toggler" type="button" data-mdb-toggle="collapse" data-mdb-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" data-action="click->dropdown#toggleMenu">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent" data-dropdown-target="menu">
      <%= link_to image_tag('rails.png', height:"15", alt:"sampleapp-logo", class: "navbar-brand mt-2 mt-lg-0"), root_path %>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item"><%= link_to "Home", root_path, class:"nav-link" %></li>
        <li class="nav-item"><%= link_to "Help", help_path, class:"nav-link" %></li>
        <li class="nav-item"><%= link_to "Toys", toys_path, class:"nav-link" %></li>
        <li class="nav-item"><%= link_to "Users", users_path, class:"nav-link" if logged_in? %> </li>
      </ul>
    </div>

    <div class="d-flex align-items-center">
      <div class="dropdown">
        <% if logged_in? %>
          <div class="dropdown">
            <a class="dropdown-toggle d-flex align-items-center hidden-arrow" id="navbarDropdownMenuAvatar" role="button" data-mb-toggle="dropdown" aria-expanded="false" data-toggle="dropdown" data-action="click->dropdown#toggle">
              <%= gravatar_for(current_user, size: 30, class: "rounded-circle")%>
            </a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuAvatar" data-dropdown-target="toggleable">
              <li><%= link_to "Profile", user_path(current_user), class: "dropdown-item", style:"color:black;"%></li>
              <li><%= link_to "Settings", edit_user_path(current_user), class: "dropdown-item", style:"color:black;"%></li>
              <li class="divider"></li>
              <li><%= link_to "Dashboard", dashboard_path, class: "dropdown-item", style:"color:black;"%></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Logout", logout_path, data: { turbo_method: :delete }, class: "dropdown-item", style:"color:black;" %>
              </li>
            </ul>
          </div>
        <% else %>
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item"><%= link_to "Login", login_path, class:"nav-link" %></li>
        </ul>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css";>
    <link href="https://unpkg.com/dropzone@6.0.0-beta.1/dist/dropzone.css" rel="stylesheet" type="text/css" />
    <%= render "layouts/default" %>
    <%= render "layouts/shim" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
    <%= render "shared/alert_notifications" %>
    <%= yield %>
    <%= render "layouts/footer" %>
    <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>